# syntax=docker/dockerfile:1

FROM python:3.12-slim

WORKDIR /api

COPY requirements.txt .
COPY .env .

RUN pip install -r requirements.txt

COPY . .

EXPOSE 8001

CMD ["uvicorn", "app.sender.main:app", "--host", "0.0.0.0", "--port", "8001"]